CREATE TABLE users (
    USERID int(11) NOT NULL AUTO_INCREMENT,
    EMAIL VARCHAR(255) DEFAULT NULL,
    FIRSTNAME VARCHAR(255) DEFAULT NULL,
    LASTNAME VARCHAR(255) DEFAULT NULL,
    PRIMARY KEY (USERID)
)ENGINE=InnoDB AUTO_INCREMENT=24 DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;